version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  trainer:
    build: .
    command: >
      python train.py --data bootstrap_news.json --out ./models/news_sentiment_pipeline
    volumes:
      - ./models:/app/models
    depends_on:
      - kafka

  spark:
    build: .
    depends_on:
      - kafka
      - trainer
    command: >
      bash -c "spark-submit --master local[*] stream_infer.py"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./models:/app/models

  producer:
    build: .
    depends_on:
      - kafka
    command: >
      python news_producer.py
    environment:
      - NEWSAPI_KEY=09fdb505f2564c3994d010119e65e242
      - BOOTSTRAP=kafka:9092

  dashboard:
    build: .
    depends_on:
      - kafka
      - spark
    ports:
      - "8501:8501"
    command: >
      streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - BOOTSTRAP=kafka:9092
