services:
  # Zookeeper
  - type: worker
    name: zookeeper
    runtime: docker
    dockerfilePath: ./Dockerfile.zookeeper
    envVars:
      - key: ZOOKEEPER_CLIENT_PORT
        value: "2181"
      - key: ZOOKEEPER_TICK_TIME
        value: "2000"

  # Kafka
  - type: worker
    name: kafka
    runtime: docker
    dockerfilePath: ./Dockerfile.kafka
    envVars:
      - key: KAFKA_BROKER_ID
        value: "1"
      - key: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - key: KAFKA_LISTENERS
        value: PLAINTEXT://0.0.0.0:9092
      - key: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT_INTERNAL://kafka:9092
      - key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - key: KAFKA_INTER_BROKER_LISTENER_NAME
        value: PLAINTEXT_INTERNAL
      - key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: "1"

  # Producer
  - type: worker
    name: producer
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEWSAPI_KEY
        value: "<set-from-dashboard-secret>"   # Docker cannot use fromSecret here
      - key: KAFKA_URL
        value: kafka:9092

  # Spark
  - type: worker
    name: spark
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KAFKA_URL
        value: kafka:9092

  # Dashboard
  - type: web
    name: dashboard
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KAFKA_URL
        value: kafka:9092
